# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-06 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysticar', '0002_auto_20190506_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_secret',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
